Update compat.ts
We're currently experiencing issues where preact-compat and enzyme-adapter-preact-pure are conflicting and causing issues:

TypeError: Cannot redefine property: type at Function.defineProperty (<anonymous>)

Adding the configurable true fixes the issue (and does the patching in the same way as preact-compat does it). https://github.com/developit/preact-compat/blob/master/src/index.js#L67